#!/usr/bin/env bash

if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ]; then
    echo "There needs to be a bucket name, a profile name, and a region provided"
    exit 1
fi

bucket_name="$1"
profile_name="$2"
region="$3"

if [ "$region" = "us-east-1" ]; then
    aws s3api create-bucket --bucket "$bucket_name" --profile "$profile_name" --region "$region" 
else
    aws s3api create-bucket --bucket "$bucket_name" --profile "$profile_name" --region "$region" --create-bucket-configuration "LocationConstraint=$region"
fi