#!/usr/bin/env bash

if [ -z "$1" ] || [ -z "$2" ]; then
    echo "There needs to be a bucket name, and a profile name provided"
    exit 1
fi

bucket_name="$1"
profile_name="$2"

aws s3 rb "s3://$bucket_name" \
    --force \
    --profile "$profile_name"