#!/usr/bin/env bash

if [ -z "$1" ] || [ -z "$2" ]; then
    echo "There needs to be a bucket name and a profile name provided"
    exit 1
fi

bucket_name="$1"
profile_name="$2"

aws s3api list-objects \
    --bucket "$bucket_name" \
    --profile "$profile_name" \
    --query "Contents[].{Key: Key, Size: Size}" \
    --output table